services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - "data:/app/world"
    environment:
      OXIDE_LISTEN_ON: "0.0.0.0:25565"
      OXIDE_WORLD_PATH: "./world"
      OXIDE_SAVE_SECONDS: "60"
      OXIDE_MOTD: "Hello oxide!"
volumes:
  data:
