name: Build, test and push

on: push

jobs:
  build_server_docker_image:
    runs-on: vm
    container:
      image: git.thetxt.io/thetxt/runner-base:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build server image
        env:
          IMAGE_TAG: git.thetxt.io/thetxt/oxide/server:${{ github.ref_name }}
        run: |
          nohup dockerd-entrypoint.sh &
          sleep 5
          docker build -t $IMAGE_TAG .
          docker save -o server_image.tar $IMAGE_TAG
      - name: Save docker image
        uses: actions/upload-artifact@v3
        with:
          name: server_image
          path: server_image.tar

  test:
    runs-on: vm
    container:
      image: git.thetxt.io/thetxt/runner-base:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: cargo test

  clippy:
    runs-on: vm
    container:
      image: git.thetxt.io/thetxt/runner-base:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run clippy
        run: |
          rustup component add --toolchain nightly clippy
          cargo clippy

  formatting:
    runs-on: vm
    container:
      image: git.thetxt.io/thetxt/runner-base:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check formatting
        run: |
          rustup component add rustfmt
          cargo fmt --check -q

  push_server:
    runs-on: vm
    container:
      image: git.thetxt.io/thetxt/runner-base:latest
    needs:
      - build_server_docker_image
      - test
      - clippy
      - formatting
    steps:
      - name: Login to forgejo registry
        uses: docker/login-action@v3
        with:
          registry: git.thetxt.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_WRITER_TOKEN }}
      - name: Download backend image
        uses: actions/download-artifact@v3
        with:
          name: server_image
      - name: Push server image
        env:
          IMAGE_TAG: git.thetxt.io/thetxt/oxide/server:${{ github.ref_name }}
        run: |
          nohup dockerd-entrypoint.sh &
          sleep 5
          docker load -i server_image.tar
          docker push $IMAGE_TAG
