name: Build, test and push

on:
  push

jobs:
  build_server_docker_image:
    runs-on: host
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build server image
        env:
          IMAGE_TAG: git.thetxt.io/thetxt/oxide/server:${{ github.ref_name }}
        run: |
          docker build -t $IMAGE_TAG .
          docker save -o server_image.tar $IMAGE_TAG
      - name: Save docker image
        uses: actions/upload-artifact@v4
        with:
          name: server_image
          path: server_image.tar

  server_test:
    runs-on: host
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test server
        working-directory: server
        run: |
          rustup toolchain install nightly --profile minimal --no-self-update
          rustup default nightly
          cargo test
  lib_test:
    runs-on: host
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test lib
        working-directory: lib
        run: |
          rustup toolchain install nightly --profile minimal --no-self-update
          rustup default nightly
          cargo test

  server_clippy:
    runs-on: host
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run clippy on server
        working-directory: server
        run: |
          rustup toolchain install nightly --profile minimal --no-self-update
          rustup default nightly
          rustup component add --toolchain nightly clippy
          cargo clippy
  lib_clippy:
    runs-on: host
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run clippy on lib
        working-directory: lib
        run: |
          rustup toolchain install nightly --profile minimal --no-self-update
          rustup default nightly
          rustup component add --toolchain nightly clippy
          cargo clippy





  push_server:
    runs-on: host
    permissions:
      packages: write
    needs:
      - build_server_docker_image
      - server_test
      - lib_test
      - server_clippy
      - lib_clippy
    steps:
      - name: Login to forgejo registry
        uses: docker/login-action@v3
        with:
          registry: git.thetxt.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download backend image
        uses: actions/download-artifact@v4
        with:
          name: server_image
      - name: Push server image
        env:
          IMAGE_TAG: git.thetxt.io/thetxt/oxide/server:${{ github.ref_name }}
        run: |
          docker load -i server_image.tar
          docker push $IMAGE_TAG
